server:
  port: 8080

# MYSQL config

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test                       # jdbc:mysql://${DB_SERVER}:3306/${DB_NAME}
#    username: root                                              # ${MYSQL_USER}
#    password: root                                              # ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

# POSTGRES config

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:5432/${DB_NAME}                   # jdbc:mysql://${DB_SERVER}:3306/${DB_NAME}
    username: ${DB_USER}                                                  # ${MYSQL_USER}
    password: ${DB_PASSWORD}                                              # ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect


# MongoDB config

#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
#      database: test
#      port    : 27017
#      host    : localhost



